package week06;
import javax.swing.*; import javax.swing.table.*; import java.awt.*;
public class MemberManagementFrame extends JFrame {
 private final JTextField id=new JTextField(10), name=new JTextField(10), phone=new JTextField(12), email=new JTextField(18); private final DefaultTableModel model=new DefaultTableModel(new String[]{"ID","이름","전화","이메일"},0); private final JTable table=new JTable(model); private final MemberDAO dao=new MemberDAO();
 public MemberManagementFrame(){setTitle("6주차 회원관리");setDefaultCloseOperation(EXIT_ON_CLOSE);setSize(720,420); JPanel form=new JPanel(); for(Component c:new Component[]{new JLabel("ID"),id,new JLabel("이름"),name,new JLabel("전화"),phone,new JLabel("이메일"),email}) form.add(c); JButton add=new JButton("등록"), edit=new JButton("수정"), del=new JButton("삭제"), refresh=new JButton("조회"); form.add(add);form.add(edit);form.add(del);form.add(refresh); add(form,BorderLayout.NORTH);add(new JScrollPane(table)); refresh.addActionListener(e->load()); add.addActionListener(e->run(()->dao.insert(read()))); edit.addActionListener(e->run(()->dao.update(read()))); del.addActionListener(e->run(()->dao.delete(id.getText().trim()))); table.getSelectionModel().addListSelectionListener(e->{int r=table.getSelectedRow();if(r>=0){id.setText(model.getValueAt(r,0).toString());name.setText(model.getValueAt(r,1).toString());phone.setText(model.getValueAt(r,2).toString());email.setText(model.getValueAt(r,3).toString());}}); load();setLocationRelativeTo(null);}
 private Member read(){return new Member(id.getText().trim(),name.getText().trim(),phone.getText().trim(),email.getText().trim());}
 private void load(){try{model.setRowCount(0);for(Member m:dao.findAll())model.addRow(new Object[]{m.memberId(),m.name(),m.phone(),m.email()});}catch(Exception ex){show(ex);}}
 interface SQLAction{int run()throws Exception;} private void run(SQLAction a){try{int n=a.run();JOptionPane.showMessageDialog(this,n+"건 처리");load();}catch(Exception ex){show(ex);}} private void show(Exception ex){JOptionPane.showMessageDialog(this,ex.getMessage(),"DB 오류",JOptionPane.ERROR_MESSAGE);}
 public static void main(String[] args){SwingUtilities.invokeLater(()->new MemberManagementFrame().setVisible(true));}
}