name: Package Week03

on:
  pull_request:
    paths:
      - 'Week03/**'
      - '.github/workflows/package-week03.yml'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload Week03 Eclipse projects
        uses: actions/upload-artifact@v4
        with:
          name: Week03_EclipseProjects
          path: Week03
          include-hidden-files: true
